server:
    port: 8080
    servlet:
        context-path: /api

spring:
    application:
        name: fundamentos01
    datasource:
        url: jdbc:postgresql://localhost:5433/devdb
        username: ups
        password: ups123
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true