# ============== PERFIL: DESARROLLO LOCAL ==============
spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/devdb
        username: ups
        password: ups123
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

logging:
    level:
        root: INFO
        ec.edu.ups.icc.fundamentos01: DEBUG
        org.hibernate.SQL: DEBUG
